# Generated by Django 4.1.1 on 2022-12-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUI', '0002_rename_student_student1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student',
        ),
    ]
